In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr2 = np.array([-1,-4,-8])
arr2

array([-1, -4, -8])

In [ ]:






arr2*-1

array([1, 4, 8])

In [ ]:







np.absolute(arr2)

array([1, 4, 8])

In [ ]:
abs(arr2)

array([1, 4, 8])

In [ ]:
arr3 = np.array(range(0,2000))

In [ ]:
arr4 = np.arange(2000)

In [ ]:
arr4.size

2000

In [ ]:
print(arr4.itemsize)

4


In [ ]:
arr4 = np.arange(2000,dtype=np.int32)

In [ ]:
print(arr4.itemsize)

4


In [ ]:
arr4 = np.arange(2000,dtype=np.int16)

In [ ]:
print(arr4.itemsize)

2


In [ ]:
arr4 = np.arange(2000,dtype=np.int8)
print(arr4.itemsize)

1


In [ ]:
arr4

array([  0,   1,   2, ..., -51, -50, -49], dtype=int8)

In [ ]:
max(arr4)

127

In [ ]:
min(arr4)

-128

In [ ]:
arr5 = np.arange(2000,dtype=np.int32)

In [ ]:
arr5

array([   0,    1,    2, ..., 1997, 1998, 1999])

In [ ]:
arr4 = np.arange(2000,dtype=np.uint8)
print(arr4.itemsize)

1


In [ ]:
arr4

array([  0,   1,   2, ..., 205, 206, 207], dtype=uint8)

In [ ]:
min(arr4)

0

In [ ]:
max(arr4)

255

In [ ]:
import time
test = 10000000
list1 = range(test)
list2 = range(test)

start = time.time()
res = [x+y for x,y in zip(list1,list2)]
end = time.time()
print(end-start)

5.248102188110352


In [ ]:
arr1 = np.arange(test)
arr2 = np.arange(test)
start = time.time()
res = arr1+arr2
end = time.time()
print(end-start)

0.8025374412536621


In [ ]:
arr = np.random.rand(3,5)

In [ ]:
arr

array([[0.81932463, 0.33917774, 0.52896861, 0.20445616, 0.09535105],
       [0.98460165, 0.15173085, 0.88224729, 0.15094215, 0.88063149],
       [0.66440774, 0.54419054, 0.71876087, 0.73091894, 0.3693663 ]])

In [ ]:
arr = np.random.rand(3,5)
arr

array([[0.10318501, 0.80178045, 0.34575678, 0.960609  , 0.51740181],
       [0.85555771, 0.11143101, 0.62360319, 0.47840026, 0.08302689],
       [0.47570977, 0.91378558, 0.01244877, 0.21777245, 0.69604318]])

In [ ]:
arr1 = np.random.randint(1,10,5)
arr1

array([6, 2, 5, 3, 7])

In [ ]:
arr1 = np.random.randint(1,10,5)
arr1

array([8, 6, 8, 2, 3])

In [ ]:
arr1 = np.random.randint(1,10,5)
arr1

array([9, 4, 3, 2, 7])

In [ ]:
arr1 = np.random.randint(15,85,(3,4))
arr1

array([[48, 18, 17, 68],
       [77, 41, 59, 50],
       [63, 75, 34, 37]])

In [ ]:
arr1 = np.random.randn(10)
arr1

array([ 0.22352903,  0.05490126, -0.83328529, -0.07207751, -0.96561803,
        0.34648985,  0.71735437,  0.96088214, -0.39852729, -0.60191381])

In [ ]:
arr1 = np.random.randn(10)
arr1

array([ 0.40109131,  1.43364514, -0.19369444,  0.13360217, -1.32827171,
        0.38054478,  0.76013365,  1.02066093, -0.10875953,  0.00889476])

In [ ]:
#### Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
### linspace
np.linspace(0,30,10)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

In [ ]:
np.linspace(0,30,50)

array([ 0.        ,  0.6122449 ,  1.2244898 ,  1.83673469,  2.44897959,
        3.06122449,  3.67346939,  4.28571429,  4.89795918,  5.51020408,
        6.12244898,  6.73469388,  7.34693878,  7.95918367,  8.57142857,
        9.18367347,  9.79591837, 10.40816327, 11.02040816, 11.63265306,
       12.24489796, 12.85714286, 13.46938776, 14.08163265, 14.69387755,
       15.30612245, 15.91836735, 16.53061224, 17.14285714, 17.75510204,
       18.36734694, 18.97959184, 19.59183673, 20.20408163, 20.81632653,
       21.42857143, 22.04081633, 22.65306122, 23.26530612, 23.87755102,
       24.48979592, 25.10204082, 25.71428571, 26.32653061, 26.93877551,
       27.55102041, 28.16326531, 28.7755102 , 29.3877551 , 30.        ])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr1=np.array([[3,5,7],
              [2,4,6]])
arr2=np.array([[10,5,3],
              [8,8,3]])
arr3=arr1+arr2
print(arr3)

[[13 10 10]
 [10 12  9]]


In [ ]:
arr1=np.array([[3,5,7],
              [2,4,6]])
arr2=np.array([[10,5,3],
              [8,8,3]])
arr3=arr1-arr2
print(arr3)

[[-7  0  4]
 [-6 -4  3]]


In [ ]:
arr1=np.array([[3,5,7],
              [2,4,6]])
arr2=np.array([[10,5,3],
              [8,8,3]])
arr3=arr1*arr2
print(arr3)

[[30 25 21]
 [16 32 18]]


In [ ]:
arr1 = np.array([[3,5,7],[2,4,6]])
arr2 = np.array([[10,5,3],[8,8,3],[1,2,3]])

In [ ]:
arr3 = arr1@arr2

In [ ]:
arr3

array([[77, 69, 45],
       [58, 54, 36]])

In [ ]:
arr1 = np.array([[3,5,7],[2,4,6]])

In [ ]:
#### constant multiplication
arr = arr1*2

In [ ]:
arr

array([[ 6, 10, 14],
       [ 4,  8, 12]])

In [ ]:
### constant division
arr2=arr/3

In [ ]:
arr2

array([[2.        , 3.33333333, 4.66666667],
       [1.33333333, 2.66666667, 4.        ]])

In [ ]:
#### constant Floor division
arr3 = arr2//2

In [ ]:
arr3

array([[1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
arr

array([[ 6, 10, 14],
       [ 4,  8, 12]])

In [ ]:
arr%2

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
arr**2

array([[ 36, 100, 196],
       [ 16,  64, 144]])

In [ ]:
lis1 = [5,8,1,3,7,15,20]

In [ ]:
lis1.index(1)

2

In [ ]:
lis1.sort()

In [ ]:
min(lis1)

1

In [ ]:
max(lis1)

20

In [ ]:
import numpy as np
arr = np.array([[5,8,1,3,7,15,20]])
print(np.sort(arr))
print(np.max(arr))
print(np.min(arr))


[[ 1  3  5  7  8 15 20]]
20
1


In [ ]:
np.sum(arr)

59

In [ ]:
arr.min()

1

In [ ]:
arr.max()

20

In [ ]:
arr.sum()

59

In [ ]:
arr.std()

6.275966467568228

In [ ]:
arr.mean()

8.428571428571429

In [ ]:
arr.var()

39.38775510204082

In [ ]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
arr.mode()

AttributeError: 'numpy.ndarray' object has no attribute 'mode'