In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2],[9,4]])
b = np.array([[8,7,-2],[5,6,-4]])
print(a.shape,b.shape)

if a.shape == b.shape:
    print("addition is possible")
    c=a+b
    print(c)
else:
    print("addition not possible")

(2, 2) (2, 3)
addition not possible


In [ ]:
a = np.array([[1,2],[9,4]])
b = np.array([[8,7],[5,6]])
print(a.shape,b.shape)

if a.shape == b.shape:
    print("addition is possible")
    c=a+b
    print(c)
else:
    print("addition not possible")

(2, 2) (2, 2)
addition is possible
[[ 9  9]
 [14 10]]


In [ ]:
a = np.array([[1,2],[9,4]])
b = np.array([[8,7,-2],[5,6,-4]])
print(a.shape,b.shape)

if a.shape[1] == b.shape[0]:
    print("Matrix Multiplication is possible")
    c=a@b
    print(c)
else:
    print("Matrix Multiplication is not possible")

(2, 2) (2, 3)
Matrix Multiplication is possible
[[ 18  19 -10]
 [ 92  87 -34]]


In [ ]:
a = np.array([[1,2],[9,4]])
b = np.array([[8,7,-2],[5,6,-4]])
print(a.shape,b.shape)
if a.shape[0] == b.shape[1]:
    c = a@b
    print(c)
else:
    print("Matrix Multiplication is not possible")

(2, 2) (2, 3)
Matrix Multiplication is not possible


In [ ]:
arr1 = np.array([[1,-2],[0,4]])
arr2 = np.array([[2,3],[6,1]])
arr1@arr2

array([[-10,   1],
       [ 24,   4]])

In [ ]:
arr1 = np.array([[1,-2],[0,4]])
arr2 = np.array([[2,3],[6,1]])
arr1*arr2

array([[ 2, -6],
       [ 0,  4]])

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8])
print(arr1)
print()
print(arr1.reshape(4,2))
print()
print(arr1.reshape(2,4))

[1 2 3 4 5 6 7 8]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
####adding elements to the existing array

arr2 = np.array([8,2,3,4,1,6,7,8])
print(arr2)
arr3 = np.append(arr2,[9,10])
print(arr3)

[8 2 3 4 1 6 7 8]
[ 8  2  3  4  1  6  7  8  9 10]


In [ ]:
#### delete element from array index wise
arr4 = np.delete(arr3,9)

In [ ]:
arr4

array([8, 2, 3, 4, 1, 6, 7, 8, 9])

In [ ]:
arr4 = np.delete(arr3,10)

IndexError: index 10 is out of bounds for axis 0 with size 10

In [ ]:
arr4

array([8, 2, 3, 4, 1, 6, 7, 8, 9])

In [ ]:
arr4 = np.delete(arr4,7)

In [ ]:
arr4

array([8, 2, 3, 4, 1, 6, 7, 9])

In [ ]:
arr4 = np.delete(arr4,1)

In [ ]:
arr4

array([8, 3, 4, 1, 6, 7, 9])

In [ ]:
arr2 = np.array([8,2,3,4,1,6,7,8])

In [ ]:
arr2

array([8, 2, 3, 4, 1, 6, 7, 8])

In [ ]:
### sorting array
arr =np.sort(arr2)

In [ ]:
arr

array([1, 2, 3, 4, 6, 7, 8, 8])

In [ ]:
print('Sin value: ',np.sin(arr))
print('\n')
print('Cos is :',np.cos(arr))
print('\n')
print('Square root :',np.sqrt(arr))
print('\n')
print('Log Values',np.log(arr))
print('\n')
print('Exponential values:',np.exp(arr))
print('\n')
print('Sum is:',np.sum(arr))
print('\n')
print('Standard Variance:',np.std(arr))
print('\n')
print('Max is:', np.max(arr))
print('\n')
print('Min is: ',np.min(arr))

Sin value:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.2794155   0.6569866
  0.98935825  0.98935825]


Cos is : [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.96017029  0.75390225
 -0.14550003 -0.14550003]


Square root : [1.         1.41421356 1.73205081 2.         2.44948974 2.64575131
 2.82842712 2.82842712]


Log Values [0.         0.69314718 1.09861229 1.38629436 1.79175947 1.94591015
 2.07944154 2.07944154]


Exponential values: [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 4.03428793e+02 1.09663316e+03 2.98095799e+03 2.98095799e+03]


Sum is: 39


Standard Variance: 2.5708704751503917


Max is: 8


Min is:  1


In [ ]:
l1 = [1,1,1,1,1,1,99,99,99,99,178,178,178]
np.unique(l1)

array([  1,  99, 178])

In [ ]:
a1 = np.array([[1,5,6],[4,7,2],[3,1,5]])

In [ ]:
a1

array([[1, 5, 6],
       [4, 7, 2],
       [3, 1, 5]])

In [ ]:
np.sum(a1)

34

In [ ]:
a1.sum(axis=0)  ### it adds all the row values in each column

array([ 8, 13, 13])

In [ ]:
a1.sum(axis=1)  ### it adds all the column values in each row

array([12, 13,  9])

In [ ]:
a1.max(axis=0)

array([4, 7, 6])

In [ ]:
a1.min(axis=0)

array([1, 1, 2])

In [ ]:
arr = np.array([[1,4,2],[3,4,6],[0,-1,5]])

In [ ]:
arr1 = np.sort(arr,axis=1)
arr1


array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [ ]:
arr1 = np.sort(arr,axis=0)
arr1

array([[ 0, -1,  2],
       [ 1,  4,  5],
       [ 3,  4,  6]])

In [ ]:
arr = np.array([10,-7,0,20,-5,1,200,40,30,1,-1,4])
arr1 = arr.reshape(3,4)
arr1


array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4]])

In [ ]:
arr2 = np.sort(arr1,axis=None)
arr2


array([ -7,  -5,  -1,   0,   1,   1,   4,  10,  20,  30,  40, 200])

In [ ]:
arr2 = np.sort(arr1,axis = 0)
arr2


array([[ -5,  -7,  -1,   4],
       [ 10,   1,   0,  20],
       [ 30,   1, 200,  40]])

In [ ]:
arr2 = np.sort(arr1,axis = 1)
arr2

array([[ -7,   0,  10,  20],
       [ -5,   1,  40, 200],
       [ -1,   1,   4,  30]])

In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[-1,-2],[-3,-4]])

In [ ]:
#### concatenation of an array
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])

In [ ]:
#### concatenation of an array
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

In [ ]:
np.vstack((arr1,arr2))

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])

In [ ]:
np.hstack((arr1,arr2))

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

In [ ]:
arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([[-1,-2],[-3,-4]])

In [ ]:
#### concatenation of an array
np.concatenate((arr1,arr2),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
#### concatenation of an array
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [-1, -2],
       [-3, -4]])

In [ ]:
np.vstack(arr1,arr2)

TypeError: vstack() takes 1 positional argument but 2 were given