In [ ]:
import numpy as np
a = np.array(range(10,22))
print(a)
print(a.shape)

[10 11 12 13 14 15 16 17 18 19 20 21]
(12,)


In [ ]:
b = a.reshape(1,12)
print(b.shape)
print(b.ndim)

(1, 12)
2


In [ ]:
b = a.reshape(12,1)
print(b.shape)
print(b.ndim)

(12, 1)
2


In [ ]:
b = a.reshape(2,6)
print(b.shape)
print(b.ndim)
print(b)

(2, 6)
2
[[10 11 12 13 14 15]
 [16 17 18 19 20 21]]


In [ ]:
b = a.reshape(6,2)
print(b.shape)
print(b.ndim)
print(b)

(6, 2)
2
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]]


In [ ]:
b = a.reshape(3,4)
print(b.shape)
print(b.ndim)
print(b)

(3, 4)
2
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [ ]:
b = a.reshape(4,3)
print(b.shape)
print(b.ndim)
print(b)

(4, 3)
2
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [ ]:
c=np.array([[10,-7,0,20],[-5,20,0,40],[30,1,-1,4],[1,2,0,4],[0,1,0,2]])
c

array([[10, -7,  0, 20],
       [-5, 20,  0, 40],
       [30,  1, -1,  4],
       [ 1,  2,  0,  4],
       [ 0,  1,  0,  2]])

In [ ]:
arr1 = np.max(c,axis = 1)
arr1

array([20, 40, 30,  4,  2])

In [ ]:
d = c.reshape(20)

In [ ]:
d

array([10, -7,  0, 20, -5, 20,  0, 40, 30,  1, -1,  4,  1,  2,  0,  4,  0,
        1,  0,  2])

In [ ]:
c.reshape(-1)

array([10, -7,  0, 20, -5, 20,  0, 40, 30,  1, -1,  4,  1,  2,  0,  4,  0,
        1,  0,  2])

In [ ]:
#### Print the values which are greater than 0 from array c
c

array([[10, -7,  0, 20],
       [-5, 20,  0, 40],
       [30,  1, -1,  4],
       [ 1,  2,  0,  4],
       [ 0,  1,  0,  2]])

In [ ]:
arr1 = c.reshape(-1)
arr1

array([10, -7,  0, 20, -5, 20,  0, 40, 30,  1, -1,  4,  1,  2,  0,  4,  0,
        1,  0,  2])

In [ ]:
#### Print the values which are greater than 0 from array arr1
arr1[arr1>0]


array([10, 20, 20, 40, 30,  1,  4,  1,  2,  4,  1,  2])

In [ ]:
arr1

array([10, -7,  0, 20, -5, 20,  0, 40, 30,  1, -1,  4,  1,  2,  0,  4,  0,
        1,  0,  2])

In [ ]:
arr1>0

array([ True, False, False,  True, False,  True, False,  True,  True,
        True, False,  True,  True,  True, False,  True, False,  True,
       False,  True])

In [ ]:
#### print the values 4 & 20

In [ ]:
arr1[(arr1>4) & (arr1<=20)]

array([10, 20, 20])

In [ ]:
temp=arr1[(arr1>4) & (arr1<=20)]
temp

array([10, 20, 20])

In [ ]:
arr2 = np.array([1,2,3,4,5,4,4,5,4,56,56,67,4])

In [ ]:
for i in range(len(arr2)):
    if arr2[i]==4:
        print(i)

3
5
6
8
12


In [ ]:
x = np.where(arr2==4)

In [ ]:
x

(array([ 3,  5,  6,  8, 12], dtype=int64),)

In [ ]:
arr2==4

array([False, False, False,  True, False,  True,  True, False,  True,
       False, False, False,  True])

In [ ]:
arr2[x]

array([4, 4, 4, 4, 4])

In [ ]:
arr2

array([ 1,  2,  3,  4,  5,  4,  4,  5,  4, 56, 56, 67,  4])

In [ ]:
#### print the indices which are divisible by 4
x = np.where(arr2%4==0)

In [ ]:
x

(array([ 3,  5,  6,  8,  9, 10, 12], dtype=int64),)

In [ ]:
arr2[x]

array([ 4,  4,  4,  4, 56, 56,  4])

In [ ]:
temp= np.where(arr2>50)

In [ ]:
arr2[temp]

array([56, 56, 67])

In [ ]:
arr=np.array([[10,-7,0,20],[-5,20,0,40],[30,1,-1,4],[1,2,0,4],[0,1,0,2]])
arr

array([[10, -7,  0, 20],
       [-5, 20,  0, 40],
       [30,  1, -1,  4],
       [ 1,  2,  0,  4],
       [ 0,  1,  0,  2]])

In [ ]:
arr_t=np.transpose(arr)

In [ ]:
print(arr)
print(arr_t)

[[10 -7  0 20]
 [-5 20  0 40]
 [30  1 -1  4]
 [ 1  2  0  4]
 [ 0  1  0  2]]
[[10 -5 30  1  0]
 [-7 20  1  2  1]
 [ 0  0 -1  0  0]
 [20 40  4  4  2]]


In [ ]:
print(arr.shape)
print(arr_t.shape)

(5, 4)
(4, 5)


In [ ]:
arr1=np.array(range(50,100))
print(arr1)
arr1.reshape(5,10)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]


array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
arr2=arr1.reshape(5,5,2)

In [ ]:
arr2

array([[[50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69]],

       [[70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89]],

       [[90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

In [ ]:
arr2=arr1.reshape(5,2,5)

In [ ]:
arr2

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])